---
- name: Scale down
  k8s_scale:
        kind: "Deployment"
        name: "{{ item }}"
        namespace: "{{ namespace }}"
        replicas: 0
  loop: "{{ services_to_scale }}"

- name: Scale up
  k8s_scale:
        kind: "Deployment"
        name: "{{ item }}"
        namespace: "{{ namespace }}"
        replicas: 1
  loop: "{{ services_to_scale }}"
